
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiwodvtyfnvbrrkqmond.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpd29kdnR5Zm52YnJya3Ftb25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODMzMjIsImV4cCI6MjA2MTk1OTMyMn0.oPzNdPnYt4gKVM72yekgpmfYjbOwqdS9dcSixeMAu_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
