// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://innpnyojhyedfrtnaxsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubnBueW9qaHllZGZydG5heHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjE4NjUsImV4cCI6MjA2OTUzNzg2NX0.DF3sGLr4JH7QmVmOcwODcyYmh5ZoRUxAcpWQG7eBasc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});